### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 93: invalid start byte

### ISSUE THREAD

**Issue by yuuSiVo** [sih4sing5hong5/hts_engine_python#5]
Hey I cant install htsengine module. Cause UnicodeDecodeError on Windows and Linux.

How can I do that

**Comment by sih4sing5hong5** [comment]
How to reproduce this error?
Can you upload the traceback?

You can try it with python 3.

**Comment by yuuSiVo** [comment]
![image](https://user-images.githubusercontent.com/26115406/35477107-b89841ee-03ff-11e8-8141-1b92ee83b274.png)
This is traceback. I tried install on Windows pip and pip3. But can't install...

![image](https://user-images.githubusercontent.com/26115406/35477123-ff917a5c-03ff-11e8-9faa-5975909dba74.png)

**Comment by sih4sing5hong5** [comment]
Your traceback with red font is very unclear. You can paste text directly instead.

**Comment by yuuSiVo** [comment]
Exception:
Traceback (most recent call last):
  File "c:\users\k017c1149\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 74, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 93: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\k017c1149\appdata\local\programs\python\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\k017c1149\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\k017c1149\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\k017c1149\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\k017c1149\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\k017c1149\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 76, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 93: invalid start byte

This is error trase back

**Comment by sih4sing5hong5** [comment]
I only found one code containing utf8. 
https://github.com/sih4sing5hong5/hts_engine_python/blob/master/setup.py#L33
Can you remove it locally before installing this package?

If not, I need your help to deploy a CI for windows environment.
